apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: solr
    spec:
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983
      containers:
      - name:
          solr
        image: "{{ .Values.webapp.images.solr }}:{{ .Values.webapp.tag }}"
        ports:
          - containerPort: 8983
            protocol: TCP
        volumeMounts:
          - name: solr-data
            mountPath: /var/solr
        livenessProbe:
          httpGet:
            path: /solr/admin/info/health
            port: 8983
          initialDelaySeconds: 20 # Give Solr time to start up
          periodSeconds: 10
          failureThreshold: 3
          # Consider a higher failureThreshold for liveness probes
        readinessProbe:
          httpGet:
            path: /solr/admin/info/health
            port: 8983
          initialDelaySeconds: 15
          periodSeconds: 5
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
