webapp:
  name: ckanprod
  group: ckanprod
  path: "/"
  tls:
    fqdn: ckanprod.data-commons.k8s.ucar.edu
    DNSAlias: data.ucar.edu
    secretName: incommon-cert-sage-ckanprod
  container:
    image: nginx
    port: 443
  images:
    solr: ghcr.io/ncar/sageprod-dashsearch-solr
    postgres: ghcr.io/ncar/sageprod-dashsearch-postgres
    nginx: ghcr.io/ncar/sageprod-dashsearch-nginx
    ckan: ghcr.io/ncar/sageprod-dashsearch-ckan
  tag: 2026-02-23.23.29